### ISSUE TITLE
[Question] Occupancy metaprofiles

### ISSUE THREAD

**Issue by jeff-godwin** [etc27/MNaseseq-workflow#1]
Hi Emma,
Thanks for the pointers in the workflow. It helped me to setup my MNase pipeline.
I just have a question regarding the occupancy plots. What do occupancy values (y-axis) 
indicate with respect to the nucleosome state? 

Do lower values indicate a nucleosome disassembly? Or are these plots to be solely used
for studying nucleosome positioning in the genome?

We are setting up the MNase protocol for the 1st time and we are exploring the downstream
analysis related to MNase-seq.

Many thanks for your help,
Jeff

**Comment by etc27** [comment]
Hi Jeff,

I'm glad you're finding the workflow useful! I have only previously used the occupancy values for studying nucleosome positioning; you can see an example of the interpretation of these results in our paper [here](https://pmc.ncbi.nlm.nih.gov/articles/PMC9516085/).

Please let me know if you have any other questions.

Emma
